apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.existingSecret }}
data:
  {{- if .Release.IsInstall }}
  {{ .Values.redis.existingSecretPasswordKey }}: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  {{ .Values.redis.existingSecretPasswordKey }}: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.redis.existingSecret )).data .Values.redis.existingSecretPasswordKey }}
  {{ end }}