apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.airflow.airflow.config.AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF }}
data:
  ROGERENV_REDISGRAPH_HOST: {{ .Release.Name }}-redis-master
  ROGERENV_REDISGRAPH_PORT: "{{ .Values.redis.master.service.port }}"
  ROGERENV_ELASTIC__SEARCH_HOST: "{{ .Values.elasticSearch.host }}"
  ROGERENV_ELASTIC__SEARCH_PORT: "{{ .Values.elasticSearch.port }}"
  ROGERENV_INDEXING_TRANQL__ENDPOINT: http://{{ include "roger.fullname" . }}-tranql-service:{{ .Values.tranql.port }}/tranql/query?dynamic_id_resolution=true&asynchronous=false
  ROGERENV_ELASTIC__SEARCH_USERNAME: elastic
